# version: '3.8'

services:

  #NOTE: this is from eprosima pulled (wget) from their website
  ubuntu-fastddsgen-eprosima:
    image: dockerrepo.eiva.com/eiva-fast-dds/ubuntu-fastdds:v3.2.2
    container_name: ubuntu-fastdds
    tty: true
    volumes:
      - ${OUTPUT_FOLDER:-./outputFolder}:/home/fastddsgen/outputFolder
      - ${INPUT_FOLDER:-./inputFolder}:/home/fastddsgen/inputFolder
    entrypoint: ["/bin/bash", "-c", "fastddsgen -d /home/fastddsgen/outputFolder /home/fastddsgen/inputFolder/*"]

# Usage:
#   OUTPUT_FOLDER=$(pwd)/myoutput FASTDDSGEN_ARGS="-input HelloWorld.idl" docker compose up <service-name>
#   OUTPUT_FOLDER=C:/absolute/path/on/windows $env:FASTDDSGEN_ARGS="-input HelloWorld.idl" docker compose up <service-name>
#
# The container will exit after running the command, and output will be in the specified host folder.
